export const cards = [
    {
        emotions: [
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
        ],
        actions: [
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
        ],
        illneses: [
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
        ],
        clothes: [
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
        ],
        animals: [
            {
                word: "cat",
                translation: "кот",
                image: "assets/images/cat.jpg",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
        ],
        food: [
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
        ],
        colors: [
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
            {
                word: "",
                translation: "",
                image: "",
                audioSrc: "",
            },
        ],
    },
];
//# sourceMappingURL=cardsInfo.js.map