export const cards = {
    house_stuff: {
        mainImage: "./images/houseStuffMain.jpg",
        data: [
            {
                word: "chair",
                translation: "стул",
                image: "./images/chair.jpg",
                audioSrc: "./sounds/chairSound.mp3",
            },
            {
                word: "table",
                translation: "стол",
                image: "./images/table.jpg",
                audioSrc: "./sounds/tableSound.mp3",
            },
            {
                word: "fridge",
                translation: "холодильник",
                image: "./images/fridge.jpg",
                audioSrc: "./sounds/fridgeSound.mp3",
            },
            {
                word: "carpet",
                translation: "ковер",
                image: "./images/carpet.jpg",
                audioSrc: "./sounds/carpetSound.mp3",
            },
            {
                word: "bed",
                translation: "кровать",
                image: "./images/bed.jpg",
                audioSrc: "./sounds/bedSound.mp3",
            },
            {
                word: "TV",
                translation: "телевизор",
                image: "./images/tv.jpg",
                audioSrc: "./sounds/tvSound.mp3",
            },
            {
                word: "wardrobe",
                translation: "шкаф",
                image: "./images/wardrobe.jpg",
                audioSrc: "./sounds/wardrobeSound.mp3",
            },
            {
                word: "sofa",
                translation: "диван",
                image: "./images/sofa.jpg",
                audioSrc: "./sounds/sofaSound.mp3",
            },
        ],
    },
    actions: {
        mainImage: "./images/actionsMain.jpg",
        data: [
            {
                word: "climb",
                translation: "взбираться",
                image: "./images/climb.jpg",
                audioSrc: "./sounds/climbSound.mp3",
            },
            {
                word: "fly",
                translation: "летать",
                image: "./images/fly.jpg",
                audioSrc: "./sounds/flySound.mp3",
            },
            {
                word: "hug",
                translation: "обнимать",
                image: "./images/hug.jpg",
                audioSrc: "./sounds/hugSound.mp3",
            },
            {
                word: "jump",
                translation: "прыгать",
                image: "./images/jump.jpg",
                audioSrc: "./sounds/jumpSound.mp3",
            },
            {
                word: "ride",
                translation: "кататься",
                image: "./images/ride.jpg",
                audioSrc: "./sounds/rideSound.mp3",
            },
            {
                word: "run",
                translation: "бегать",
                image: "./images/run.jpg",
                audioSrc: "./sounds/runSound.mp3",
            },
            {
                word: "sing",
                translation: "петь",
                image: "./images/sing.jpg",
                audioSrc: "./sounds/singSound.mp3",
            },
            {
                word: "swim",
                translation: "плавать",
                image: "./images/swim.jpg",
                audioSrc: "./sounds/swimSound.mp3",
            },
        ],
    },
    diseases: {
        mainImage: "./images/deseases.jpg",
        data: [
            {
                word: "cold",
                translation: "простуда",
                image: "./images/cold.jpg",
                audioSrc: "./sounds/coldSound.mp3",
            },
            {
                word: "cough",
                translation: "кашель",
                image: "./images/cough.jpg",
                audioSrc: "./sounds/coughSound.mp3",
            },
            {
                word: "headache",
                translation: "головная боль",
                image: "./images/headache.jpg",
                audioSrc: "./sounds/headacheSound.mp3",
            },
            {
                word: "itchy",
                translation: "зуд",
                image: "./images/itchy.jpg",
                audioSrc: "./sounds/itchySound.mp3",
            },
            {
                word: "sneeze",
                translation: "насморк",
                image: "./images/sneeze.jpg",
                audioSrc: "./sounds/sneezeSound.mp3",
            },
            {
                word: "sore throat",
                translation: "боль в горле",
                image: "./images/sore_throat.jpg",
                audioSrc: "./sounds/sore_throatSound.mp3",
            },
            {
                word: "stomachache",
                translation: "боль в животе",
                image: "./images/stomachache.jpg",
                audioSrc: "./sounds/stomachacheSound.mp3",
            },
            {
                word: "toothache",
                translation: "зубная боль",
                image: "./images/toothache.jpg",
                audioSrc: "./sounds/toothacheSound.mp3",
            },
        ],
    },
    clothes: {
        mainImage: "./images/clothesMain.jpg",
        data: [
            {
                word: "cap",
                translation: "кепка",
                image: "./images/cap.jpg",
                audioSrc: "./sounds/capSound.mp3",
            },
            {
                word: "dress",
                translation: "платье",
                image: "./images/dress.jpg",
                audioSrc: "./sounds/dressSound.mp3",
            },
            {
                word: "shirt",
                translation: "рубашка",
                image: "./images/shirt.jpg",
                audioSrc: "./sounds/shirtSound.mp3",
            },
            {
                word: "shorts",
                translation: "шорты",
                image: "./images/shorts.jpg",
                audioSrc: "./sounds/shortsSound.mp3",
            },
            {
                word: "skirt",
                translation: "юбка",
                image: "./images/skirt.jpg",
                audioSrc: "./sounds/skirtSound.mp3",
            },
            {
                word: "sweater",
                translation: "свитер",
                image: "./images/sweater.jpg",
                audioSrc: "./sounds/sweaterSound.mp3",
            },
            {
                word: "t-shirt",
                translation: "футболка",
                image: "./images/t-shirt.jpg",
                audioSrc: "./sounds/t-shirtSound.mp3",
            },
            {
                word: "trousers",
                translation: "брюки",
                image: "./images/trousers.jpg",
                audioSrc: "./sounds/trousersSound.mp3",
            },
        ],
    },
    animals: {
        mainImage: "./images/animalsMain.jpg",
        data: [
            {
                word: "cat",
                translation: "кот",
                image: "./images/cat.jpg",
                audioSrc: "./sounds/catSound.mp3",
            },
            {
                word: "dog",
                translation: "собака",
                image: "./images/dog.jpg",
                audioSrc: "./sounds/dogSound.mp3",
            },
            {
                word: "bear",
                translation: "медведь",
                image: "./images/bear.jpg",
                audioSrc: "./sounds/bearSound.mp3",
            },
            {
                word: "cow",
                translation: "корова",
                image: "./images/cow.jpg",
                audioSrc: "./sounds/cowSound.mp3",
            },
            {
                word: "fish",
                translation: "рыба",
                image: "./images/fish.jpg",
                audioSrc: "./sounds/fishSound.mp3",
            },
            {
                word: "fox",
                translation: "лиса",
                image: "./images/fox.jpg",
                audioSrc: "./sounds/foxSound.mp3",
            },
            {
                word: "mouse",
                translation: "мышь",
                image: "./images/mouse.jpg",
                audioSrc: "./sounds/mouseSound.mp3",
            },
            {
                word: "sheep",
                translation: "овца",
                image: "./images/sheep.jpg",
                audioSrc: "./sounds/sheepSound.mp3",
            },
        ],
    },
    food: {
        mainImage: "./images/foodMain.jpg",
        data: [
            {
                word: "apple",
                translation: "яблоко",
                image: "./images/apple.jpg",
                audioSrc: "./sounds/appleSound.mp3",
            },
            {
                word: "banana",
                translation: "банан",
                image: "./images/banana.jpg",
                audioSrc: "./sounds/bananaSound.mp3",
            },
            {
                word: "cherry",
                translation: "вишня",
                image: "./images/cherry.jpg",
                audioSrc: "./sounds/cherrySound.mp3",
            },
            {
                word: "bread",
                translation: "хлеб",
                image: "./images/bread.jpg",
                audioSrc: "./sounds/breadSound.mp3",
            },
            {
                word: "chocolate",
                translation: "шоколад",
                image: "./images/chocolate.jpg",
                audioSrc: "./sounds/chocolateSound.mp3",
            },
            {
                word: "strawberry",
                translation: "клубника",
                image: "./images/strawberry.jpg",
                audioSrc: "./sounds/strawberrySound.mp3",
            },
            {
                word: "pear",
                translation: "груша",
                image: "./images/pear.jpg",
                audioSrc: "./sounds/pearSound.mp3",
            },
            {
                word: "tomato",
                translation: "помидор",
                image: "./images/tomato.jpg",
                audioSrc: "./sounds/tomatoSound.mp3",
            },
        ],
    },
    colors: {
        mainImage: "./images/colorsMain.jpg",
        data: [
            {
                word: "black",
                translation: "черный",
                image: "./images/black.jpg",
                audioSrc: "./sounds/blackSound.mp3",
            },
            {
                word: "blue",
                translation: "голубой",
                image: "./images/blue.jpg",
                audioSrc: "./sounds/blueSound.mp3",
            },
            {
                word: "green",
                translation: "зеленый",
                image: "./images/green.jpg",
                audioSrc: "./sounds/greenSound.mp3",
            },
            {
                word: "orange",
                translation: "оранжевый",
                image: "./images/orange.jpg",
                audioSrc: "./sounds/orangeSound.mp3",
            },
            {
                word: "pink",
                translation: "розовый",
                image: "./images/pink.jpg",
                audioSrc: "./sounds/pinkSound.mp3",
            },
            {
                word: "purple",
                translation: "фиолетовый",
                image: "./images/purple.jpg",
                audioSrc: "./sounds/purpleSound.mp3",
            },
            {
                word: "red",
                translation: "красный",
                image: "./images/red.jpg",
                audioSrc: "./sounds/redSound.mp3",
            },
            {
                word: "yellow",
                translation: "желтый",
                image: "./images/yellow.jpg",
                audioSrc: "./sounds/yellowSound.mp3",
            },
        ],
    },
    transport: {
        mainImage: "./images/transportMain.jpg",
        data: [
            {
                word: "airplane",
                translation: "самолет",
                image: "./images/airplane.jpg",
                audioSrc: "./sounds/airplaneSound.mp3",
            },
            {
                word: "bus",
                translation: "автобус",
                image: "./images/bus.jpg",
                audioSrc: "./sounds/busSound.mp3",
            },
            {
                word: "car",
                translation: "машина",
                image: "./images/car.jpg",
                audioSrc: "./sounds/carSound.mp3",
            },
            {
                word: "helicopter",
                translation: "вертолет",
                image: "./images/helicopter.jpg",
                audioSrc: "./sounds/helicopterSound.mp3",
            },
            {
                word: "motorcycle",
                translation: "мотоцикл",
                image: "./images/motorcycle.jpg",
                audioSrc: "./sounds/motorcycleSound.mp3",
            },
            {
                word: "ship",
                translation: "корабль",
                image: "./images/ship.jpg",
                audioSrc: "./sounds/shipSound.mp3",
            },
            {
                word: "taxi",
                translation: "такси",
                image: "./images/taxi.jpg",
                audioSrc: "./sounds/taxiSound.mp3",
            },
            {
                word: "train",
                translation: "поезд",
                image: "./images/train.jpg",
                audioSrc: "./sounds/trainSound.mp3",
            },
        ],
    },
};
//# sourceMappingURL=cardsInfo.js.map